### ISSUE TITLE
Config file for CityScapes

### ISSUE THREAD

**Issue by edizhuang** [yassouali/pytorch_segmentation#14]
Hi Yassine,

Did you train on CityScapes and what the config file should be? Thanks!

**Comment by yassouali** [comment]
Hi, I guess you only need to add the mode (fine or coarse) make sure you use bigger base and crop sizes given the size of the CS images; here is an example:

```python
    "train_loader": {
        "type": "CityScapes",
        "args":{
            "data_dir": "/data/Cityscapes",
            "batch_size": 8,
            "base_size": 1024,
            "crop_size": 512,
            "augment": true,
            "shuffle": true,
            "scale": true,
            "flip": true,
            "rotate": true,
            "blur": false,
            "split": "train",
            "mode": "fine",
            "num_workers": 8
        }
    },

    "val_loader": {
        "type": "CityScapes",
        "args":{
            "data_dir": "/data/Cityscapes",
            "batch_size": 1,
            "val": true,
            "split": "val",
            "mode": "fine",
            "num_workers": 4
        }
    }
```

**Comment by edizhuang** [comment]
Hi Yassine,

Thanks for the quick reply. I see the original image size is 2018 * 1024, so here what's the input size and patch size for training? For validation are you using the original size?

**Comment by edizhuang** [comment]
Hi Yassine,

Thanks for the quick reply. I see the original image size is 2018 * 1024, so here what's the input size and patch size for training? For validation are you using the original size?


Best,

Chengyuan


________________________________

**Comment by yassouali** [comment]
First step is to resize the bigger size to 1024 (so 1024 x 512) then a scaling then a random crop of 512 x 512, for validation you can either take crops of 1024 with a bigger batch for quick processing, or use the original size with a batch of 1, accurate but slow.

**Comment by edizhuang** [comment]
Thanks!

**Comment by edizhuang** [comment]
Thanks!

By the way, I got this error when using 4 GPUs:  ValueError: Caught ValueError in replica 3 on device 3.

Use one GPU is OK.

  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/storage/scratch2/cz0056/city/yassouali-deeplab/base/base_trainer.py", line 98, in train
    results = self._train_epoch(epoch)
  File "/storage/scratch2/cz0056/city/yassouali-deeplab/trainer.py", line 56, in _train_epoch
    output = self.model(data)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 3 on device 3.
Original Traceback (most recent call last):
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage/scratch2/cz0056/city/yassouali-deeplab/models/deeplabv3_plus.py", line 357, in forward
    x = self.ASSP(x)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/storage/scratch2/cz0056/city/yassouali-deeplab/models/deeplabv3_plus.py", line 291, in forward
    x5 = F.interpolate(self.avg_pool(x), size=(x.size(2), x.size(3)), mode='bilinear', align_corners=True)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/cm/shared/utils/PYTHON/pytorch-gpu1.2.0/lib/python3.6/site-packages/torch/nn/functional.py", line 1652, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])


________________________________

**Comment by yassouali** [comment]
With 4 GPUs, maybe the batch size is say 7, in this case each GPU will have 2 Images but the last one with one image, and his will give you an error, try a batch size = GPUs * 2 at least.
