### ISSUE TITLE
URL broken for ResNet50, 101, 152

### ISSUE THREAD

**Issue by XZLeo** [yassouali/pytorch_segmentation#155]
First of all, thank authors for the neat repo!

 When I tested "type": "UNetResnet" and "backbone": "resnet50",  there is a bug caused by bad url in [this line](
https://gitlab.liu.se/zilxi06/tsbb19_semantic_segmentation/-/blob/master/models/resnet.py?ref_type=heads#L24)
I got this error.
```
python train.py --config config.json
python train.py --config config.json
Downloading: "https://s3.us-west-1.wasabisys.com/encoding/models/resnet50s-a75c83cf.zip" to ./pretrained/resnet50s-a75c83cf.zip
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 's3.us-west-1.wasabisys.com'. (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 60, in <module>
    main(config, args.resume)
  File "train.py", line 25, in main
    model = get_instance(models, 'arch', config, train_loader.dataset.num_classes)
  File "train.py", line 15, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/unet.py", line 129, in __init__
    model = getattr(resnet, backbone)(pretrained, norm_layer=nn.BatchNorm2d)
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/resnet.py", line 264, in resnet50
    model.load_state_dict(load_url(model_urls['resnet50'], model_dir=root))
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/resnet.py", line 300, in load_url
    urlretrieve(url, cached_file)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 's3.us-west-1.wasabisys.com'. (_ssl.c:1131)>
```
Apparently, the link is broken. I tried to replace it with [this link]('https://download.pytorch.org/models/resnet50-19c8e357.pth') found in [this page](https://pytorch.org/vision/0.8/_modules/torchvision/models/resnet.html). However, I got another error. How to fix this? Thank you.
```
python train.py --config config.json
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to ./pretrained/resnet50-19c8e357.zip
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    main(config, args.resume)
  File "train.py", line 25, in main
    model = get_instance(models, 'arch', config, train_loader.dataset.num_classes)
  File "train.py", line 15, in get_instance
    return getattr(module, config[name]['type'])(*args, **config[name]['args'])
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/unet.py", line 129, in __init__
    model = getattr(resnet, backbone)(pretrained, norm_layer=nn.BatchNorm2d)
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/resnet.py", line 264, in resnet50
    model.load_state_dict(load_url(model_urls['resnet50'], model_dir=root))
  File "/home/zilxi06/teaching/tsbb19_semantic_segmentation/models/resnet.py", line 301, in load_url
    zip_ref = zipfile.ZipFile(cached_file, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by yassouali** [comment]
Just checked, the links seem to work, can you please double check?
