### ISSUE TITLE
An erroe "mean is not a valid value for reduction".

### ISSUE THREAD

**Issue by jjy91234** [yassouali/pytorch_segmentation#23]
Hi,I think your code is nice and detailed, but when I run it , a error was happend as follow:

Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/home/lilier/code/pytorch_segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/lilier/code/pytorch_segmentation/trainer.py", line 60, in _train_epoch
    loss = self.loss(output[0], target)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lilier/code/pytorch_segmentation/utils/losses.py", line 30, in forward
    loss = self.CE(output, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1409, in nll_loss
    return torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 30, in get_enum
    raise ValueError(reduction + " is not a valid value for reduction")
ValueError: mean is not a valid value for reduction

How can I solve it,thank you!

**Comment by yassouali** [comment]
Hi, were you able to solve this ?

**Comment by jjy91234** [comment]
Yes,I have solved it, thank you! The code is datiled and easy to run. Buy the way ,is I will get the val result after training？so there is no val.py here?

**Comment by yassouali** [comment]
in the config file you have `val_per_epochs`, it'll run each `val_per_epochs` during training
