### ISSUE TITLE
TypeError about np.ndarray  when training PSPNet for the first time

### ISSUE THREAD

**Issue by ustcychu** [yassouali/pytorch_segmentation#31]
After configuring the environement as required (win10, anaconda3, python3.6.9, pytorch1.1.0, cuda9.0, torchvision0.3.0, etc.), I want to use the command "python train.py --config config.json" to train a PSP model on the dataset VOC (I have not changed the config.json), but with the following bug:

(There are many informations about PSPNet and config file...)

Detected GPUs: 1 Requested: 1

  0%|                                                                                                    | 0/1323 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "C:\Users\USTC\capstone\dl frame\pytorch_segmentation\base\base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "C:\Users\USTC\capstone\dl frame\pytorch_segmentation\trainer.py", line 49, in _train_epoch
    for batch_idx, (data, target) in enumerate(tbar):
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\tqdm\_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "C:\Users\USTC\capstone\dl frame\pytorch_segmentation\base\base_dataloader.py", line 76, in __iter__
    self.preload()
  File "C:\Users\USTC\capstone\dl frame\pytorch_segmentation\base\base_dataloader.py", line 64, in preload
    self.next_input, self.next_target = next(self.loaditer)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\USTC\capstone\dl frame\pytorch_segmentation\base\base_dataset.py", line 132, in __getitem__
    label = torch.from_numpy(np.array(label, dtype=np.int32)).long()
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

so, what can I do to solve this? I am a beginner...

**Comment by yassouali** [comment]
Hi, this problem is specific to windows, can you try installing the latest numpy version ?
another solution is to use `float32`.

replace ` label = torch.from_numpy(np.array(label, dtype=np.int32)).long()`
with ` label = torch.from_numpy(np.array(label, dtype=np.float32)).long()`

**Comment by ustcychu** [comment]
OK the latter works out. Thank you very much~
