### ISSUE TITLE
data read

### ISSUE THREAD

**Issue by starkcn** [yassouali/pytorch_segmentation#34]
0%|                                                                                                     | 0/291 [00:00<?, ?it/s]/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
TRAIN (1) | Loss: 0.334 | Acc 0.92 mIoU 0.69 | B 0.62 D 0.03 |:  27%|███████▋                    | 80/291 [00:49<01:51,  1.90it/s]Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/home/caffe/语义分割/pytorch_segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/caffe/语义分割/pytorch_segmentation/trainer.py", line 49, in _train_epoch
    for batch_idx, (data, target) in enumerate(tbar):
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "/home/caffe/语义分割/pytorch_segmentation/base/base_dataloader.py", line 81, in __iter__
    self.preload()
  File "/home/caffe/语义分割/pytorch_segmentation/base/base_dataloader.py", line 64, in preload
    self.next_input, self.next_target = next(self.loaditer)
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/caffe/语义分割/pytorch_segmentation/base/base_dataset.py", line 126, in __getitem__
    image, label, image_id = self._load_data(index)
  File "/home/caffe/语义分割/pytorch_segmentation/dataloaders/voc.py", line 37, in _load_data
    image = np.asarray(Image.open(image_path), dtype=np.float32)
  File "/home/caffe/anaconda3/envs/pytorch/lib/python3.6/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOC-200-200-0/VOCdevkit/VOC2012/JPEGImages/.jpg'

**Comment by starkcn** [comment]
the picture is *.jpg,but i do not know the problem

**Comment by yassouali** [comment]
My guess is that one of the files names is empty, remove it from the variables in `self.files`
`self.files = [i for i in self.files if len(i) > 0]`

**Comment by starkcn** [comment]
sorry，i do not know that mens.i should remove the one&nbsp; of the pictures names or not.em …the picture name have the space，that couse the code can not read the name of picture

---Original---

**Comment by yassouali** [comment]
Was the issue solved ?
