### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

### ISSUE THREAD

**Issue by DarrenmondZhang** [yassouali/pytorch_segmentation#41]
Hi, I missed a problem when  first ran this code.  **The Model printed successfully**
![image](https://user-images.githubusercontent.com/44083987/72160972-39a24d80-33fa-11ea-96e6-882af76689aa.png)

**But Problems happened during training**

Detected GPUs: 1 Requested: 1

  0%|                                                                                                    | 0/1323 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "G:\pytorch_segmentation\base\base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "G:\pytorch_segmentation\trainer.py", line 49, in _train_epoch
    for batch_idx, (data, target) in enumerate(tbar):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\tqdm\_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "G:\pytorch_segmentation\base\base_dataloader.py", line 76, in __iter__
    self.preload()
  File "G:\pytorch_segmentation\base\base_dataloader.py", line 64, in preload
    self.next_input, self.next_target = next(self.loaditer)
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\pytorch_segmentation\base\base_dataset.py", line 132, in __getitem__
    label = torch.from_numpy(np.array(label, dtype=np.int32)).long()
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.
![image](https://user-images.githubusercontent.com/44083987/72161080-65253800-33fa-11ea-8b82-4ad95bf2ad98.png)

Looking forward to your reply.Thanks

**Comment by yassouali** [comment]
This is the same issue as in https://github.com/yassouali/pytorch_segmentation/issues/31#issue-533712628

See a possible solution: https://github.com/yassouali/pytorch_segmentation/issues/31#issuecomment-562510155
