### ISSUE TITLE
File(s) not found

### ISSUE THREAD

**Issue by Murmeltier105** [yassouali/pytorch_segmentation#65]
When running the train.py I get an error like this:
`  0%|                                                                                                    | 0/1323 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/trainer.py", line 49, in _train_epoch
    for batch_idx, (data, target) in enumerate(tbar):
  File "/home/dr1/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/base/base_dataloader.py", line 76, in __iter__
    self.preload()
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/base/base_dataloader.py", line 64, in preload
    self.next_input, self.next_target = next(self.loaditer)
  File "/home/dr1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/dr1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/dr1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dr1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/base/base_dataset.py", line 126, in __getitem__
    image, label, image_id = self._load_data(index)
  File "/home/dr1/sds_hd/sd18a006/Daniel/Programmieren/pytorch_segmentation/dataloaders/voc.py", line 64, in _load_data
    label = np.asarray(Image.open(label_path), dtype=np.int32)
  File "/home/dr1/.local/lib/python3.6/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/SegmentationClassAug/2011_001926.png'
The exact name of the picture varies each time. Is it due to a problem with the VOC-Dataset or code-related?

**Comment by yassouali** [comment]
Hi, 

I think you only need to give the correct path to pascal VOC, did you download the dataset in `data/`.

can you simply check if `'data/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/SegmentationClassAug/2011_001926.png'` exists?
