### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ZYMXIXI** [yassouali/pytorch_segmentation#77]
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main(config, args.resume)
  File "train.py", line 42, in main
    trainer.train()
  File "pytorch_segmentation-master/base/base_trainer.py", line 101, in train
    results = self._train_epoch(epoch)
  File "/pytorch_segmentation-master/trainer.py", line 72, in _train_epoch
    loss.backward()
  File "/anaconda3/envs/water/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/envs/water/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

**Comment by yassouali** [comment]
Hi, this issue is due to some error when initializing CUDNN, I think it is related to your setup.

I would suggest reinstalling PyTroch and/or CUDA and trying again.

**Comment by blair2020** [comment]
网上说的都没用，我昨天遇到这个问题等半个小时自动就好，应该是之前GPU占用正在释放
